---
name: skeleton-config
---
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Dynamic\ElementalTemplates\Extension\BaseElementDataExtension

SilverStripe\CMS\Controllers\CMSPageAddController:
    extensions:
        - Dynamic\ElementalTemplates\Extension\CMSPageAddControllerExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Dynamic\ElementalTemplates\Extension\SiteTreeExtension